### ISSUE TITLE
Specify the required version of Zig in the README

### ISSUE THREAD

**Issue by ducdetronquito** [Vexu/zuri#2]
Hi @Vexu !

Would it be possible to specify the required version of Zig to work with *zuri* ? (v0.6.0 or master)
If it is the master branch, what are the reasons to use it over the last stable release ?

Have a nice day ! :)

**Comment by Vexu** [comment]
Here you go: 8f5a0bf00ba583b39ddac21c11fd8461e56ab60f. Zig master version is used by default since that's what majority of Zig users use due to it being required by the language server.

**Comment by ducdetronquito** [comment]
Thank you :)
