### ISSUE TITLE
mapQuery: make `;` an optional separator?

### ISSUE THREAD

**Issue by jedisct1** [Vexu/zuri#9]
Hi!

Currently, `mapQuery()` considers `;` as a query parameters separator, like `&`.

The current situation is a little bit messy: https://github.com/golang/go/issues/25192#issuecomment-789799446

Do you think `;` should be made optional (either via another parameter or another function) in `zuri`?

**Comment by Vexu** [comment]
> Do you think `;` should be made optional

I wouldn't mind removing it entirely, based on that thread it seems hardly anyone ever used them.

**Comment by jedisct1** [comment]
Sounds like a reasonable thing to do.
